apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-mysql-operator
  namespace: default
spec:
  displayName: My SQL Operator
  publisher: Arch POC
  sourceType: grpc
  image: quay.io/mpaulgreen/mysql-operator-catalog:v0.0.2 
  updateStrategy:
    registryPoll:
      interval: 1m
